[tool.poetry]
name = "otsukare"
version = "0"
description = "Otsukare is a web application to help Japanese language students study."
license = "MIT"
authors = ["Nick Jenkins"]
readme = "README.md"
homepage = "https://www.ndjenkins.com/projects/otsukare/"
repository = "https://github.com/ndjenkins85/otsukare/"
documentation = "https://ndjenkins85.github.io/otsukare/"
keywords = [
    "python",
    "heroku",
    "japanese_language",
    "japanese_study"
    ]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Education",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Documentation :: Sphinx",
]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.12,<4"
sphinx = {version = "^8.2", optional = true}
Flask = "^3.1"
Flask-WTF = "^1.2"
pandas = "^2.2"
WTForms = "^3.2"
gunicorn = "^23.0"
Werkzeug = "^3.1"
SQLAlchemy = "^2.0"
Flask-SQLAlchemy = "^3.1"
psycopg2-binary = "^2.9"
lxml = "^5.3"
beautifulsoup4 = "^4.13"
requests = "^2.32"
urllib3 = "^2.3"
chardet = "^5.2"
certifi = "^2025.1"
duolingo-api = "^0.5.4"
tqdm = "^4.67"
openpyxl = "^3.1"
python-jose = "^3.5"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.3"
black = "^25.1"
jupyter = "^1.1"
ipython = "^8.32"
m2r2 = "^0.3.1"
mypy = "^1.15"
nox = "^2025.2"
pytest = "^8.3"
pytest-cov = "^6.0"
pre-commit = "^4.1"
sphinx-rtd-theme = "^3.0"
sphinx-autodoc-typehints = "^3.1"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.poetry.scripts]
otsukare = 'otsukare:app'

[tool.poetry-version-plugin]
source = "init"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_local_folder = ["otsukare"]
skip_glob = [
    "otsukare/__init__.py",
    "otsukare/my_forms.py",
    "otsukare/views.py"
    ]

[tool.mypy]
python_version = 3.12

[[tool.mypy.overrides]]
module = [
    'sphinx_rtd_theme',
    'jose',
    'nox.*',
    'pytest',
    ]
ignore_missing_imports = true

[tool.coverage.run]
parallel = true
source = [
    "otsukare",
    "tests",
    "noxfile.py",
    "docs/conf.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@overload",
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
]
